# DISCLAIMER: THIS IS A TEST FILE GENERATED BY AI


from direct.showbase.ShowBase import ShowBase
from panda3d.core import Vec4, Vec2
import numpy as np

# Assuming the uploaded files are in the same directory/package
from radix16 import Radix16FFT
from graphing.graph import Graph

class FFTGraphApp(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)
        
        # 1. Initialize FFT (Requires a power of 16 for this specific implementation)
        self.N = 256 # 16^2
        self.fft_engine = Radix16FFT(self)
        
        # We set max_val to a level appropriate for the expected FFT magnitude
        self.spectrum_graph = Graph(
            parent=self.aspect2d,
            min_val=0.0,
            max_val=self.N / 2, # Normalized magnitude ceiling
            max_values=self.N // 2, # Only show positive frequencies (Nyquist)
            line_color=Vec4(0.2, 0.8, 1.0, 1.0), # Cyan line
            bg_color=Vec4(0, 0, 0, 0.8),
            position=Vec2(0, 0),
            size=Vec2(2.4, 1.2),
            thickness=2.0
        )
        
        # 3. State variables for signal generation
        self.frame_counter = 0
        
        # Add the update task to the engine
        self.taskMgr.add(self.update_signal_task, "UpdateSignalTask")

    def update_signal_task(self, task):
        # --- PHASE 1: Signal Generation ---
        # Create a time window that shifts every frame
        t = np.linspace(0, 1, self.N) + (self.frame_counter * 0.01)
        
        # Create two frequencies: 50Hz and a drifting high frequency
        freq2 = 80 + 20 * np.sin(self.frame_counter * 0.05)
        signal = np.sin(2 * np.pi * 50 * t) + 0.5 * np.sin(2 * np.pi * freq2 * t)
        signal += 0.2 * np.random.randn(self.N) # Add noise
        
        # --- PHASE 2: GPU FFT Processing ---
        # Upload, process, and fetch results
        gpu_handle = self.fft_engine.fft(signal.astype(np.complex64))
        complex_result = self.fft_engine.fetch(gpu_handle)
        
        # --- PHASE 3: Visualization ---
        # Calculate Magnitude Spectrum
        # We only need the first half (0 to Nyquist frequency)
        magnitudes = np.abs(complex_result[:self.N // 2])
        
        # Clear the graph and 'put' the new spectrum data
        self.spectrum_graph.clear()
        for val in magnitudes:
            self.spectrum_graph.put(val)
            
        self.frame_counter += 1
        return task.cont

if __name__ == "__main__":
    app = FFTGraphApp()
    app.run()
